name: Release

on:
  push:
    tags: 
    - 'v[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

  build_release:
    runs-on: ubuntu-latest
    needs: create_release

    steps:
    - uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2

    - name: Setup ODM
      uses: johanfylling/setup-odm@v1
      with:
        version: latest

    - name: Build
      run: odm build -v

    - name: Upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./build/bundle.tar.gz
        asset_name: bundle.tar.gz
        asset_content_type: application/gzip
